apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: eureka-server
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eureka-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: eureka-server
    spec:
      containers:
        - env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka-server:8761/eureka
            - name: eureka.instance.hostname
              value: eureka-server
          image: vforce1520/eureka-service-image:latest
          name: eureka-server
          ports:
            - containerPort: 8761
              protocol: TCP
      hostname: eureka-server
      restartPolicy: Always
