apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: gateway-service
  name: gateway-service
spec:
  ports:
    - name: "8769"
      port: 8769
      targetPort: 8769
  selector:
    io.kompose.service: gateway-service
