apiVersion: v1
kind: Namespace
metadata:
  name: microservices

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldata
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: vforce1520/eureka-service-image:latest
          ports:
            - containerPort: 8761
          env:
            - name: eureka_instance_hostname
              value: eureka-server
            - name: eureka_client_serviceUrl_defaultZone
              value: http://eureka-server:8761/eureka

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: vforce1520/order-service-image:latest
          ports:
            - containerPort: 8763
          env:
            - name: spring_datasource_url
              value: jdbc:mysql://mysqldb:3306/order_schema?allowPublicKeyRetrieval=true
            - name: eureka_client_serviceUrl_defaultZone
              value: http://eureka-server:8761/eureka
          volumeMounts:
            - name: m2-volume
              mountPath: /root/.m2
      volumes:
        - name: m2-volume
          emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: vforce1520/product-service-image:latest
          ports:
            - containerPort: 8762
          env:
            - name: spring_datasource_url
              value: jdbc:mysql://mysqldb:3306/product_schema?allowPublicKeyRetrieval=true
            - name: eureka_client_serviceUrl_defaultZone
              value: http://eureka-server:8761/eureka
          volumeMounts:
            - name: m2-volume
              mountPath: /root/.m2
      volumes:
        - name: m2-volume
          emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: vforce1520/payment-service-image:latest
          ports:
            - containerPort: 8764
          env:
            - name: spring_datasource_url
              value: jdbc:mysql://mysqldb:3306/payment_schema?allowPublicKeyRetrieval=true
            - name: eureka_client_serviceUrl_defaultZone
              value: http://eureka-server:8761/eureka
          volumeMounts:
            - name: m2-volume
              mountPath: /root/.m2
      volumes:
        - name: m2-volume
          emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: vforce1520/user-service-image:latest
          ports:
            - containerPort: 8765
          env:
            - name: spring_datasource_url
              value: jdbc:mysql://mysqldb:3306/user_schema?allowPublicKeyRetrieval=true
            - name: eureka_client_serviceUrl_defaultZone
              value: http://eureka-server:8761/eureka
          volumeMounts:
            - name: m2-volume
              mountPath: /root/.m2
      volumes:
        - name: m2-volume
          emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: vforce1520/gateway-service-image:latest
          ports:
            - containerPort: 8769
          env:
            - name: eureka_client_serviceUrl_defaultZone
              value: http://eureka-server:8761/eureka

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql:8.2
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: order_schema
            - name: MYSQL_ROOT_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - name: mysqldata
              mountPath: /var/lib/mysql
      volumes:
        - name: mysqldata
          persistentVolumeClaim:
            claimName: mysqldata

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq-log
              mountPath: /var/log/rabbitmq
      volumes:
        - name: rabbitmq-data
          emptyDir: {}
        - name: rabbitmq-log
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: microservices
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: eureka-server

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: microservices
spec:
  type: NodePort
  ports:
    - port: 8763
      targetPort: 8763
  selector:
    app: order-service

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: microservices
spec:
  type: NodePort
  ports:
    - port: 8762
      targetPort: 8762
  selector:
    app: product-service

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: microservices
spec:
  type: NodePort
  ports:
    - port: 8764
      targetPort: 8764
  selector:
    app: payment-service

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: microservices
spec:
  type: NodePort
  ports:
    - port: 8765
      targetPort: 8765
  selector:
    app: user-service

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: microservices
spec:
  type: NodePort
  ports:
    - port: 8769
      targetPort: 8769
  selector:
    app: gateway-service

---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  namespace: microservices
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysqldb

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: microservices
spec:
  type: NodePort
  ports:
    - name: rabbitmq
      port: 5672
      targetPort: 5672
    - name: rabbitmq-management
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq