apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: order-service
  name: order-service
spec:
  ports:
    - name: "8763"
      port: 8763
      targetPort: 8763
  selector:
    io.kompose.service: order-service
