apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: payment-service
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: payment-service
    spec:
      containers:
        - env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka-server:8761/eureka
            - name: spring.datasource.url
              value: jdbc:mysql://mysqldb:3306/payment_schema?allowPublicKeyRetrieval=true
          image: vforce1520/payment-service-image:latest
          name: payment-service
          ports:
            - containerPort: 8764
              protocol: TCP
          volumeMounts:
            - mountPath: /root/.m2
              name: payment-service-claim0
      restartPolicy: Always
      volumes:
        - name: payment-service-claim0
          persistentVolumeClaim:
            claimName: payment-service-claim0
