apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: product-service
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: product-service
    spec:
      containers:
        - env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka-server:8761/eureka
            - name: spring.datasource.url
              value: jdbc:mysql://mysqldb:3306/product_schema?allowPublicKeyRetrieval=true
          image: vforce1520/product-service-image:latest
          name: product-service
          ports:
            - containerPort: 8762
              protocol: TCP
          volumeMounts:
            - mountPath: /root/.m2
              name: product-service-claim0
      restartPolicy: Always
      volumes:
        - name: product-service-claim0
          persistentVolumeClaim:
            claimName: product-service-claim0
